### ISSUE TITLE
Criação do Projeto e Definição da Estrutura de Diretórios

### ISSUE THREAD

**Issue by lupamedeiros** [lupamedeiros/pong-mobile-version#2]
# Criação do projeto no Unity e definição da estrutura de diretórios

Nesta tarefa deverá ser:

- [ ] Criado o Projeto Mobile 2D utilizando Unity (definir versão do Unity utilizada);
- [x] Atualizado o README.md do reporitório indicando: Versão da Engine; Estrutura de Diretórios utilizada;

**Comment by n1sek0** [comment]
Ainda não está esteticamente agradável, irei fazer mais modificações no README.
